### ISSUE TITLE
google chrome will not start and no errors shown

### ISSUE THREAD

**Issue by webciter** [zhuyingda/webster#12]
google chrome will not start and no errors shown

if i use plain crawler method it works ok.

**Comment by zhuyingda** [comment]
Could you give me more detail? os, system version, node version and npm version.

The part of Google Chrome is depend on `Puppeteer`, you can check if the installation script of `puppeteer` works fine.

If your environment is hard to deploy `puppeteer`, you can use `docker` to deploy this project.
[docker image](https://hub.docker.com/r/zhuyingda/webster-demo/)

Feel free to contact me if you need. :)
