### ISSUE TITLE
Does webster supports concurrency feature?

### ISSUE THREAD

**Issue by nikan1996** [zhuyingda/webster#3]
I am finding a headless browser which supports concurrent requests, does webster supports this feature?

**Comment by zhuyingda** [comment]
Yeah, of course.
The Webster is designed to support concurrent requests, it has a task queue which implement by redis. Your concurrent requests would be push to the queue and you can set the concurrency by init some number of queue consumer (spider instance), the more you init your consumers, the fast you can finish your concurrent work.
