### ISSUE TITLE
请教作者，针对selenium的反爬措施，对此框架有用吗

### ISSUE THREAD

**Issue by 82kg** [zhuyingda/webster#8]
例如"window.navigator.webdriver"，在非selenium环境下其值为undefined，以及其他很多标志性字符串、都能被反爬虫 检测到。

**Comment by zhuyingda** [comment]
反爬虫的策略，靠标记位和环境变量的手段是很业余的， 我在几年前的[文章](https://segmentfault.com/a/1190000012293292)中就阐述过，因为js运行的宿主环境chromium靠攻击者所掌控，简单的环境变量很容易通过在执行页面之前预注入一些逻辑bypass。
这个框架并不是针对爬虫的攻防而开发的，但理论上基于puppeteer的任何爬虫都可以通杀你所说的反爬机制。

**Comment by 82kg** [comment]
> 反爬虫的策略，靠标记位和环境变量的手段是很业余的， 我在几年前的[文章](https://segmentfault.com/a/1190000012293292)中就阐述过，因为js运行的宿主环境chromium靠攻击者所掌控，简单的环境变量很容易通过在执行页面之前预注入一些逻辑bypass。
> 这个框架并不是针对爬虫的攻防而开发的，但理论上基于puppeteer的任何爬虫都可以通杀你所说的反爬机制。

测试了一下，好像绕不过 reCaptcha

**Comment by zhuyingda** [comment]
嗯 reCaptcha是基于机器学习的bot-detect，基于设备指纹采集和云端聚类做的， 不过对抗的方案也不少，随便一搜 [就有很多](https://anti-captcha.com/)。
